apiVersion: v1
kind: Secret
metadata:
  name: vehicle-secrets
type: Opaque
stringData:
  mysql-root-password: "password"
  database-url: "mysql+pymysql://root:password@vehicle-mysql:3306/vehicle_logs"